"""Data source parsers and collection orchestration package.

Exposes all parser functions, constants, and collection entry points for
complete backward compatibility.
"""

from .barchart import (
    _BARCHART_MONTH_CODES,
    _MONTH_ABBREVIATIONS,
    _barchart_contract_months,
    parse_barchart_coal,
)
from .base import (
    fetch,
    label_from_name,
    parse_barchart_price_change,
    parse_table_pages,
    resolve_parser,
)
from .bloomberg import (
    BLOOMBERG_AGRICULTURE_URL,
    BLOOMBERG_BRENT_URL,
    BLOOMBERG_DXY_URL,
    BLOOMBERG_EURUSD_URL,
    BLOOMBERG_METALS_URL,
    BLOOMBERG_TIN_URL,
    BLOOMBERG_USDIDR_URL,
    BLOOMBERG_WTI_URL,
    _bloomberg_market_item,
    _decimal,
    _fetch_bloomberg_html,
    _next_data_page_props,
    _parse_bloomberg_quote,
    _parse_bloomberg_sections_html,
    parse_bloomberg_agriculture,
    parse_bloomberg_agriculture_html,
    parse_bloomberg_brent,
    parse_bloomberg_dxy,
    parse_bloomberg_eurusd,
    parse_bloomberg_metals,
    parse_bloomberg_metals_html,
    parse_bloomberg_quote_html,
    parse_bloomberg_tin,
    parse_bloomberg_usdidr,
    parse_bloomberg_usdidr_html,
    parse_bloomberg_wti,
)
from .bursa import parse_bursa_cpo, parse_bursa_cpo_payload
from .cnbc import parse_cnbc_quote_html, parse_cnbc_quote_pages
from .collector import collect_data
from .constants import (
    CNBC_US_INDEX_KEYS,
    CNBC_US_INDEX_PAGES,
    COMMODITY_FUTURES_KEYS,
    IDX_INDEX_KEYS,
    IDX_SECTOR_KEYS,
    INVESTING_MAJOR_INDEX_KEYS,
    MAJOR_INDEX_KEYS,
    REQUESTED_SOURCE_BY_KEY,
    US_BOND_KEYS,
)
from .indonesia import (
    _previous_business_day,
    parse_indonesia_bonds,
    parse_indonesia_cds,
    parse_indonesia_cds_payload,
    parse_jisdor,
    parse_phei,
)
from .investing import parse_commodities_futures, parse_instrument_page
from .news import fetch_market_news
from .sunsirs import (
    SUNSIRS_AMMONIA_URL,
    parse_ammonia,
    parse_sunsirs_ammonia_html,
    parse_sunsirs_woodpulp,
)
from .yahoo import (
    parse_yahoo_finance,
    parse_yahoo_idx_property,
    parse_yahoo_sector_indices,
)

__all__ = [
    "BLOOMBERG_AGRICULTURE_URL",
    "BLOOMBERG_BRENT_URL",
    "BLOOMBERG_DXY_URL",
    "BLOOMBERG_EURUSD_URL",
    "BLOOMBERG_METALS_URL",
    "BLOOMBERG_TIN_URL",
    "BLOOMBERG_USDIDR_URL",
    "BLOOMBERG_WTI_URL",
    "CNBC_US_INDEX_KEYS",
    "CNBC_US_INDEX_PAGES",
    "COMMODITY_FUTURES_KEYS",
    "IDX_INDEX_KEYS",
    "IDX_SECTOR_KEYS",
    "INVESTING_MAJOR_INDEX_KEYS",
    "MAJOR_INDEX_KEYS",
    "REQUESTED_SOURCE_BY_KEY",
    "SUNSIRS_AMMONIA_URL",
    "US_BOND_KEYS",
    "_BARCHART_MONTH_CODES",
    "_MONTH_ABBREVIATIONS",
    "_barchart_contract_months",
    "_bloomberg_market_item",
    "_decimal",
    "_fetch_bloomberg_html",
    "_next_data_page_props",
    "_parse_bloomberg_quote",
    "_parse_bloomberg_sections_html",
    "_previous_business_day",
    "collect_data",
    "fetch",
    "fetch_market_news",
    "label_from_name",
    "parse_ammonia",
    "parse_barchart_coal",
    "parse_barchart_price_change",
    "parse_bloomberg_agriculture",
    "parse_bloomberg_agriculture_html",
    "parse_bloomberg_brent",
    "parse_bloomberg_dxy",
    "parse_bloomberg_eurusd",
    "parse_bloomberg_metals",
    "parse_bloomberg_metals_html",
    "parse_bloomberg_quote_html",
    "parse_bloomberg_tin",
    "parse_bloomberg_usdidr",
    "parse_bloomberg_usdidr_html",
    "parse_bloomberg_wti",
    "parse_bursa_cpo",
    "parse_bursa_cpo_payload",
    "parse_cnbc_quote_html",
    "parse_cnbc_quote_pages",
    "parse_commodities_futures",
    "parse_indonesia_bonds",
    "parse_indonesia_cds",
    "parse_indonesia_cds_payload",
    "parse_instrument_page",
    "parse_jisdor",
    "parse_phei",
    "parse_sunsirs_ammonia_html",
    "parse_sunsirs_woodpulp",
    "parse_table_pages",
    "parse_yahoo_finance",
    "parse_yahoo_idx_property",
    "parse_yahoo_sector_indices",
    "resolve_parser",
]
